export const BLOG_LAYOUT = {
  GRID: {
    FEATURED_MOBILE_COLS: 1,
    FEATURED_TABLET_COLS: 2,
    FEATURED_DESKTOP_COLS: 3,
    POSTS_GAP: 4,
    FEATURED_GAP: 4,
  },
  SPACING: {
    SECTION_MARGIN_TOP: 12,
    HEADER_MARGIN_BOTTOM: 6,
    SEARCH_MARGIN_BOTTOM: 10,
  },
} as const;

